<a href="https://colab.research.google.com/github/VanNguyenThiCam/Frameworks/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR


* numpy thao tác trên mảng đa chiều và hỗ trợ được nhiều thứ 

* numpy chỉ chạy được trên CPU, người ta cần tìm cái tương tự numpy là tensor chạy được trên GPU

* tensorflow có thể chạy được trên cả CPU và GPU



In [4]:
import tensorflow as tf

print(tf.__version__) #kiểm tra version tensorflow trên google colab

print(tf.config.list_physical_devices('GPU')) #kiểm tra có chạy trên GPU không

2.8.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


# Đưa một list numpy về dạng tensor


**Ví dụ 1** 

In [5]:
import tensorflow as tf
import numpy as np

In [7]:
a_list = [1,2,3,4]
data_np = np.array(a_list)

print(data_np)
print(type(data_np))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
#chuyển từ nparray tới tensor

a_tensor = tf.convert_to_tensor(a_list)
print(a_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


**Ví dụ 2**

In [14]:
#tạo mảng 2x3
import tensorflow as tf
import numpy as np
a_array = np.array([[1,2],[2,3],[5,6]])
print(a_array)

a_tensor = tf.convert_to_tensor(a_array)
print(a_tensor)

print(a_tensor.shape) #in ra kích cỡ của tensor

print(a_tensor.dtype) #in ra loại của của tensor

print(a_tensor.ndim) #in ra số chiều của tensor

[[1 2]
 [2 3]
 [5 6]]
tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int64)
(3, 2)
<dtype: 'int64'>
2


# Một số hàm hay sử dụng 