<a href="https://colab.research.google.com/github/VanNguyenThiCam/Frameworks/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR


* numpy thao tác trên mảng đa chiều và hỗ trợ được nhiều thứ 

* numpy chỉ chạy được trên CPU, người ta cần tìm cái tương tự numpy là tensor chạy được trên GPU

* tensorflow có thể chạy được trên cả CPU và GPU



In [ ]:
import tensorflow as tf

print(tf.__version__) #kiểm tra version tensorflow trên google colab

print(tf.config.list_physical_devices('GPU')) #kiểm tra có chạy trên GPU không

2.8.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


# Đưa một list numpy về dạng tensor


**Ví dụ 1** 

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
a_list = [1,2,3,4]
data_np = np.array(a_list)

print(data_np)
print(type(data_np))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#chuyển từ nparray tới tensor

a_tensor = tf.convert_to_tensor(a_list)
print(a_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


**Ví dụ 2**

In [ ]:
#tạo mảng 2x3
import tensorflow as tf
import numpy as np
a_array = np.array([[1,2],[2,3],[5,6]])
print(a_array)

a_tensor = tf.convert_to_tensor(a_array)
print(a_tensor)

print(a_tensor.shape) #in ra kích cỡ của tensor

print(a_tensor.dtype) #in ra loại của của tensor

print(a_tensor.ndim) #in ra số chiều của tensor

[[1 2]
 [2 3]
 [5 6]]
tf.Tensor(
[[1 2]
 [2 3]
 [5 6]], shape=(3, 2), dtype=int64)
(3, 2)
<dtype: 'int64'>
2


In [ ]:
a_list = [1,2,3,4]
a_tensor_reshape = tf.reshape(tf.convert_to_tensor(a_list),(2,2))
print(a_tensor_reshape)
print(a_tensor_reshape.shape)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
(2, 2)


# Broadcasting

Khi lấy tensor cộng cho 1 số/ tensor không cùng shape thì

* Con số đó được chuyển đổi cùng shape với tensor để nó thực hiện phép cộng.

* Tensor không cùng shape cũng được biến thành cùng shape để thực hiện phép cộng



**Ví dụ 1**

In [ ]:
import tensorflow as tf
import numpy as np

tensor_1 = tf.convert_to_tensor([[1,2],[3,4]])
tensor_2 = tf.convert_to_tensor(1)

tensor_3 = tensor_1 + tensor_2

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)
print('tensor_3: \n', tensor_3)

tensor_1: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tensor_2: 
 tf.Tensor(1, shape=(), dtype=int32)
tensor_3: 
 tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


**Ví dụ 2**

In [ ]:
import tensorflow as tf
import numpy as np

np_data = np.array(range(1,13)).reshape(4,3)
tensor_1 = tf.convert_to_tensor(np_data)

tensor_2 = tf.convert_to_tensor([1,0,1])

#tensor_3 = tensor_1 + tensor_2 #khác kiểu không thể cộng

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)
#print('tensor_3: \n', tensor_3)

tensor_1: 
 tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int64)
tensor_2: 
 tf.Tensor([1 0 1], shape=(3,), dtype=int32)


In [ ]:
#Cách khắc phục là ép kiểu

import tensorflow as tf
import numpy as np

np_data = np.array(range(1,13)).reshape(4,3)
tensor_1 = tf.convert_to_tensor(np_data)

tensor_2 = tf.convert_to_tensor([1,0,1],dtype = tf.int64)

tensor_3 = tensor_1 + tensor_2 #khác kiểu không thể cộng

print('tensor_1: \n', tensor_1)
print('tensor_2: \n', tensor_2)
print('tensor_3: \n', tensor_3)

tensor_1: 
 tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int64)
tensor_2: 
 tf.Tensor([1 0 1], shape=(3,), dtype=int64)
tensor_3: 
 tf.Tensor(
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]], shape=(4, 3), dtype=int64)


# Một số hàm quan trọng

**Squared Difference**

In [ ]:
import tensorflow as tf

x = [1,2,3,4]
y = 5

sd = tf.math.squared_difference(x,y)
print(sd)




tf.Tensor([16  9  4  1], shape=(4,), dtype=int32)


In [ ]:
x = tf.convert_to_tensor([1,2,3,4])
y = 5

sd = tf.math.squared_difference(x,y)
print(sd)

tf.Tensor([16  9  4  1], shape=(4,), dtype=int32)


In [ ]:
import tensorflow as tf
import numpy as np

x = np.array([1,2,3,4])
y = 5

sd = tf.math.squared_difference(x,y)
print(sd)

tf.Tensor([16  9  4  1], shape=(4,), dtype=int64)


**Sử dụng hàm sinh ra tensor phân phối chuẩn, đều**

In [ ]:
#hàm này sau này ứng dụng để sinh ra theta ngẫu nhiên

import tensorflow as tf

rand = tf.random.normal(shape = (3,2), mean = 0, stddev= 1)
print(rand)

tf.Tensor(
[[ 1.2609682   0.12188428]
 [ 0.32075056  0.00384439]
 [ 0.4563132  -0.7065491 ]], shape=(3, 2), dtype=float32)


In [ ]:
import tensorflow as tf

rand = tf.random.uniform(shape = (3,2), minval = 0,maxval = 9,dtype =tf.int32)

print(rand)

tf.Tensor(
[[3 8]
 [7 1]
 [6 7]], shape=(3, 2), dtype=int32)


**Hàm ghép 2 tensor**

In [ ]:
import tensorflow as tf

tensor_1 = tf.random.normal(shape =(2,2),mean = 0, stddev= 1)
tensor_2 = tf.random.normal(shape =(2,2),mean = 0, stddev= 1)

tensor_3 = tf.concat([tensor_1,tensor_2],axis = 0) #ghép theo dòng

tensor_4 = tf.concat([tensor_1,tensor_2],axis = 1) #ghép theo cột

print(tensor_1)
print(tensor_2)
print(tensor_3)
print(tensor_4)
print(tensor_1.shape)
print(tensor_2.shape)
print(tensor_3.shape)
print(tensor_4.shape)

tf.Tensor(
[[ 1.2365433  -0.87453663]
 [-0.00853013 -0.797084  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.4537518   0.98249143]
 [-0.44948336  0.7668248 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.2365433  -0.87453663]
 [-0.00853013 -0.797084  ]
 [-1.4537518   0.98249143]
 [-0.44948336  0.7668248 ]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[ 1.2365433  -0.87453663 -1.4537518   0.98249143]
 [-0.00853013 -0.797084   -0.44948336  0.7668248 ]], shape=(2, 4), dtype=float32)
(2, 2)
(2, 2)
(4, 2)
(2, 4)


**Hàm argmin/ argmax**

axis = 0 là lấy theo cột, axis = 1 là lấy theo dòng

*   argmin kết quả trả về VỊ TRÍ mà có giá trị nhỏ nhất
*   argmax kết quả trả về VỊ TRÍ mà có giá trị lớn nhất



In [ ]:
import tensorflow as tf

tensor = tf.random.uniform(shape = (3,6), minval = 0, maxval = 20,dtype = tf.int32)

min_position_1 = tf.argmin(tensor,axis = 0) #lấy theo cột 
min_position_2 = tf.argmin(tensor,axis = 1) # lấy theo dòng

print(tensor)
print(min_position_1)
print(min_position_2)

tf.Tensor(
[[ 4 14 12  4 10  2]
 [10  0  9 12  3  8]
 [ 9 18  1 16  7  1]], shape=(3, 6), dtype=int32)
tf.Tensor([0 1 2 0 1 2], shape=(6,), dtype=int64)
tf.Tensor([5 1 2], shape=(3,), dtype=int64)


In [ ]:
import tensorflow as tf

tensor = tf.random.uniform(shape = (3,6), minval = 0, maxval = 20,dtype = tf.int32)

max_position_1 = tf.argmax(tensor,axis = 0) #lấy theo cột 
max_position_2 = tf.argmax(tensor,axis = 1) # lấy theo dòng

print(tensor)
print(max_position_1)
print(max_position_2)

tf.Tensor(
[[19 16  7  7 11 11]
 [ 9  6  7  7  4 17]
 [11  6 12 19  6 18]], shape=(3, 6), dtype=int32)
tf.Tensor([0 0 2 2 0 2], shape=(6,), dtype=int64)
tf.Tensor([0 5 3], shape=(3,), dtype=int64)


**Nhân hai ma trận**



*   @
*   matmul



**Ví dụ 1**

In [ ]:
import tensorflow as tf
import numpy as np

matrix1 = tf.convert_to_tensor([[1,2],[3,4]])
matrix2 = tf.convert_to_tensor([[2,3],[2,1]])

result1 = matrix1@matrix2
print(result1)

result2 = matrix2@matrix1
print(result2)

tf.Tensor(
[[ 6  5]
 [14 13]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[11 16]
 [ 5  8]], shape=(2, 2), dtype=int32)


**Ví dụ 2**

In [3]:
import tensorflow as tf
import numpy as np

matrix = tf.convert_to_tensor([[1,2],[3,4]])
vector = tf.convert_to_tensor([1,2])

print(matrix1.shape)
print(vector.shape)

vector = tf.reshape(vector,(2,1)) #để nhân hai ma trận thì phải đưa vecto về ma trận 2x1

print(vector.shape)
result1 = tf.matmul(matrix1,vector)
print(result1)


result2 = tf.matmul(tf.transpose(vector),matrix)
print(result2)        


(2, 2)
(2,)
(2, 1)
tf.Tensor(
[[ 5]
 [11]], shape=(2, 1), dtype=int32)
tf.Tensor([[ 7 10]], shape=(1, 2), dtype=int32)


***Hàm Variable***



*   Tạo vector tham số
*   Nó có thể thay thế bằng giá trị khác



**Ví dụ 1**

In [2]:
import tensorflow as tf

var = tf.Variable([1.0,2.0])
print(var.numpy())

var.assign([7,9])
print(var.numpy())

[1. 2.]
[7. 9.]


**Ví dụ 2**

In [3]:
import tensorflow as tf 

var = tf.Variable([1.0,2.0])

var.assign_add([5,3])
print(var.numpy())

var.assign_sub([2,3])
print(var.numpy())

[6. 5.]
[4. 2.]


***Hàm GradientTape***

Tính đạo hàm 

**Ví dụ 1**    Cho 

$X = \begin{bmatrix}
x_1 & x_2 \\
x_3 & x_4
\end{bmatrix}$

$y = x_1 + x_2 + x_3 + x_4$, $z = y^2$
Tính $\frac{dz}{dx}$


**Giải** 

$\frac{dz}{dx_1}=\frac{dz}{dy}\frac{dy}{dx_1} = 2y$

In [4]:
import tensorflow as tf

x = tf.ones((2,2))

with tf.GradientTape() as t:
    t.watch(x) #quan sát biến x, tại vì tính đạo hàm theo biến x
    y = tf.reduce_sum(x)
    z = tf.multiply(y,y)


dz_dx = t.gradient(z,x)

print(x)

print(dz_dx)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


**Ví dụ 2**

Cho $x, y = x^2, z = y^2$. Tính $\frac{dz}{dx}$

In [6]:
import tensorflow as tf 

x = tf.constant(3.0)

with tf.GradientTape(persistent= True) as t: #muốn tính đạo hàm nhiều lần, persistent = True
    t.watch(x) #tính đạo hàm theo x
    y = x*x
    z = y*y

dz_dx = t.gradient(z,x)
dy_dx = t.gradient(y,x)

print(dz_dx)
print(dy_dx)

tf.Tensor(108.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


**Ví dụ 3**

Cho $y = x^3$. Tính $y^{'}, y^{''}$

In [7]:
import tensorflow as tf

x = tf.Variable(1.0)

with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        y = x*x*x

    dy_dx = t2.gradient(y,x)
d2y_dx2 = t1.gradient(dy_dx,x)

print(dy_dx)
print(d2y_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


**Ví dụ 4:** Áp dụng GradientTape vào bài toán Linear Regression


In [11]:
import tensorflow as tf

w = tf.Variable([-0.34]) # các trọng số của mô hình mình dùng Variable để thay đổi trực tiếp
b = tf.Variable([0.04])

x = [6.7,4.6,3.5,5.5]
x = tf.convert_to_tensor(x)

print('b: \n', b.numpy())
print('w: \n', w.numpy())
print('x: \n', x.numpy())


with tf.GradientTape(persistent=True) as Tape:
    y = tf.math.multiply(x,w)+b
    print('y: \n',y.numpy())

    loss = tf.reduce_mean(y**2)
    print('loss: \n', loss.numpy())

b: 
 [0.04]
w: 
 [-0.34]
x: 
 [6.7 4.6 3.5 5.5]
y: 
 [-2.238     -1.524     -1.1500001 -1.83     ]
loss: 
 3.0006552
